import type {
  ProfileData,
  NavItem,
  Technology,
  Experience,
  Project,
  ContactLink,
} from "../types";

export const profileMock: ProfileData = {
  name: "David Felicio",
  username: "daweronn",
  role: "Fullstack Developer",
  tagline: "Simplicity is the ultimate form of sophistication.",
  bio: "Fullstack developer focused on React, TypeScript and Python. I build interfaces that respect the user and systems that respect the team.",
  avatarUrl: null,
  location: "Rio de Janeiro, Brazil",
  availableForWork: true,
  socials: [
    { id: "github", label: "GitHub", url: "https://github.com/daweronn", icon: "github" },
    { id: "linkedin", label: "LinkedIn", url: "https://www.linkedin.com/in/davidvicter/", icon: "linkedin" },
    { id: "instagram", label: "Instagram", url: "https://www.instagram.com/davidvicter/", icon: "instagram" },
  ],
};

export const navItemsMock: NavItem[] = [
  { id: "sobre", label: "About" },
  { id: "projetos", label: "Projects" },
  { id: "experiencia", label: "Experience" },
  { id: "tecnologias", label: "Technologies" },
  { id: "contato", label: "Contact" },
];

export const aboutParagraphsMock: string[] = [
  "I'm a fullstack developer passionate about building products that combine simplicity and robustness. I believe the best interface is the one the user doesn't even notice — it just works.",
  "I work mainly with React, TypeScript and Python, always focused on clean architecture, performance and user experience. I enjoy projects that challenge and have real impact.",
  "Outside of code, I'm driven by design, music and the idea that well-crafted technology can change how people live.",
];

export const technologiesMock: Technology[] = [
  { label: "React", category: "Frontend" },
  { label: "Next.js", category: "Frontend" },
  { label: "TypeScript", category: "Linguagem" },
  { label: "Python", category: "Linguagem" },
  { label: "Tailwind CSS", category: "Frontend" },
  { label: "FastAPI", category: "Backend" },
  { label: "PostgreSQL", category: "Banco de Dados" },
  { label: "Supabase", category: "Banco de Dados" },
  { label: "Docker", category: "DevOps" },
  { label: "Git", category: "DevOps" },
  { label: "Framer Motion", category: "Frontend" },
  { label: "Node.js", category: "Backend" },
];

export const experiencesMock: Experience[] = [
  {
    id: "exp-1",
    role: "Fullstack Developer",
    company: "Freelance",
    period: "2023 — Present",
    description:
      "Full-cycle web application development for clients across different segments, focused on React, Next.js and Python. System architecture, interface design and third-party API integrations.",
  },
  {
    id: "exp-2",
    role: "Frontend Developer",
    company: "Personal Project",
    period: "2022 — 2023",
    description:
      "Built personal digital products exploring design systems, performance and accessibility. Deepened expertise in TypeScript and component architecture.",
  },
];

export const projectsMock: Project[] = [
  {
    id: "proj-skorpion",
    slug: "skorpion",
    title: "Skorpion Gamer — Members Platform",
    description:
      "Automations within the members platform of the Skorpion Gamer YouTube channel.",
    longDescription:
      "The system centralizes member access to an ecosystem of data and analytics generated by Python automations — collection, processing and delivery in an interactive dashboard, all within a single authenticated environment.",
    stack: ["React", "TypeScript", "Python", "Supabase"],
    url: "https://skorpiongamer.com.br",
    year: "2026",
    status: "live",
  },
  {
    id: "proj-2",
    slug: "em-breve",
    title: "Coming soon",
    description: "New projects coming soon.",
    longDescription:
      "I'm working on new projects that will be added here shortly. Keep an eye on my GitHub for updates.",
    stack: ["In development"],
    year: "2025",
    status: "wip",
  },
];

export const contactLinksMock: ContactLink[] = [
  {
    id: "email",
    label: "Email",
    description: "davidvicter@gmail.com",
    href: "mailto:davidvicter@gmail.com",
    icon: "mail",
    external: false,
  },
  {
    id: "github",
    label: "GitHub",
    description: "@daweronn",
    href: "https://github.com/daweronn",
    icon: "github",
    external: true,
  },
  {
    id: "linkedin",
    label: "LinkedIn",
    description: "davidvicter",
    href: "https://www.linkedin.com/in/davidvicter/",
    icon: "linkedin",
    external: true,
  },
  {
    id: "instagram",
    label: "Instagram",
    description: "@davidvicter",
    href: "https://www.instagram.com/davidvicter/",
    icon: "instagram",
    external: true,
  },
];